### ISSUE TITLE
OpenWRT issues

### ISSUE THREAD

**Issue by Naxulanth** [42Kmi/LagDrop#4]
Hello, I'm trying to run LagDrop on OpenWRT, unfortunately with many troubles along the way.

Steps I have taken so far:

I created a static lease for my PS4 through /etc/config/dhcp
I copied the script files to /root/lagdrop (I also tried placing them to /jffs, even though I doubt it makes a difference?), set permissions (tried both 755/777)

At this point, I had problems because the script couldnt create the directory/options file, so I created them manually and filled the options file with the info you posted in another issue.

Tried running the script again (lagdrop_ps4) which disconnects my router from the internet until next reboot while giving me a multitude of errors. I'm very much stuck at this point and I would highly appreciate your help. I'm attaching screenshots of the errors I am getting incase it could be helpful.

![image](https://user-images.githubusercontent.com/28110882/40353767-f2d48132-5dba-11e8-9180-9df18145e2b8.png)

The errors just keep repeating themselves until I reboot the router.

**Comment by Naxulanth** [comment]
So apparently there's no nvram command in OpenWRT, and some other missing files compared to DD-WRT I suppose... Is there any way I could fix this by changing the script?

**Comment by Naxulanth** [comment]
Updates:

I modified the script so that it doesn't use nvram anymore, passed the LAN and WAN IP manually for now, I'll switch it around to uci (which openwrt uses) later on if needs be.

I swapped the paths with 'ip_conntrack' in it to 'nf_conntrack' as I believe they are the same (correct me if I'm mistaken) since ip_conntrack doesnt exist even though the module seems to be loaded on modprobe.

I've slimmed down the errors to :
![image](https://user-images.githubusercontent.com/28110882/40357836-09c88874-5dc6-11e8-86f8-c3f56035af78.png)

I'm sending you a modified version of the script as well. Please let me know if I did anything wrong.

https://0bin.net/paste/cfbBU7ViFggdRJBX#n-glqKmin44hpq/xx1+SiS562m/P6WhnEr98fQzKb9g

**Comment by 42Kmi** [comment]
Thanks using LagDrop, and thanks good your tenacity. I honestly haven't
thoroughly tested it in OpenWRT, so thanks for your feedback.

I've been busy with medical school for the longest, so I haven't had much
time to focus on LagDrop, but I've been working on it's latest unreleased
version for while now. I may have corrected some issues you found already,
but if not, I can still them into my current inflated build (vet 3.0.0, aka
All for One). Version 3.0.0 combines all the server filters versions into 1
script, is much faster, and includes some other features. I've been working
out some bugs I would encounter and testing some ideas that I thought would
be useful.

I tested LagDrop on the Chaos Calmer build of OpenWRT, on which things were
fine until I eventually encountered permission denied errors. I think many
of those are safe guards to protect the router.

**Comment by Naxulanth** [comment]
Thank you for your reply

I managed to solve most of the problems, the permission errors were all file related as far as I could tell, they went away when I manually created whitelist and blacklist files. 

Right now my problem is that whenever I run LagDrop once, my router completely loses internet connection until I reboot the router. I would highly appreciate it if you have any info to share with me regarding this issue.

Have a good day!

**Comment by 42Kmi** [comment]
I remember have LagDrop clear the iptables when it initially runs. See if
removing that line solves the problem.

**Comment by Naxulanth** [comment]
Yeah, I was looking into just that as well :) Flushing the forward table causes the issue, also, the lines with

iptables -P LDACCEPT ACCEPT
iptables -P LDREJECT DROP

don't really work since you can't add policies to custom chains from what iptables tells me.

I'll remove the line where it flushes the table and see what happens.

**Comment by Naxulanth** [comment]
Doesn't look like filtering is working :( I joined a couple of games with no allowed or blocked peers

**Comment by 42Kmi** [comment]
iptables -P LDACCEPT ACCEPT
iptables -P LDREJECT DROP

Those lines are needed for the default behaviors of LagDrop. LagDrop tests
and sorts peer IP addresses into those tables.

**Comment by Naxulanth** [comment]
Running those lines gives an error of:

Bad built-in chain name.

The -P switch only works for default chains (FORWARD, INPUT, OUTPUT)

**Comment by 42Kmi** [comment]
Thanks for your time and effort.
Could you run iptables --help and send me the output?

**Comment by 42Kmi** [comment]
Could you send your modifcations again? I was unable to get to the pastebin
before it expired.

**Comment by Naxulanth** [comment]
Hello!

![image](https://user-images.githubusercontent.com/28110882/40469324-d7142234-5f38-11e8-80b4-95de42ed42e1.png)

![image](https://user-images.githubusercontent.com/28110882/40469386-05aa5bb8-5f39-11e8-8149-049f9c77e65b.png)

These screenshots are from my Raspberry Pi since I don't have access to my router right now, but the error I was getting on the router is exactly the same.

https://0bin.net/paste/LMVMDC1psHIR-IDE#JmuoIocQTABCfuXISre09dx+PpXd0WvBoAI4TcyHMfa

Here's a new paste, if I remember correct I haven't tampered with the whitelist/blacklist files so it could still be throwing the permission denied warnings.

In this paste I just edited the lines which my router didn't have (such as nvram, where I replace the IP with manual values instead, and nf_conntrack instead of ip_conntrack). I also removed the lines we have talked about earlier (with the -P)

If I also remember correct, line 86 is causing one of the permission errors as well. (there were 3 total)

I don't believe the permission problems explain why the script doesn't work, as it should be even without the whitelist/blacklist functions if I'm not mistaken?

Also, while I was running the lagdropcount script, I noticed that there were warnings every now and then about xtables lock.

IPTABLES: Another app is currently holding the xtables lock. <- this would be the error

Thank you very much for your time once again.

**Comment by 42Kmi** [comment]
Thanks. Could you open a terminal and press tab twice to list all the
programs and send that to me?

Looking on my end, I actually fixed the nf_conntrack issue a long time ago,
just hadn't uploaded it, haha. LagDrop 3.0.0 checks if you're in OpenWRT or
DD-WRT and adjusts accordingly.

I'll try to finish updating my manual and push a beta soon

**Comment by 42Kmi** [comment]
I just pushed the Version 3.0.0 beta. Please check it out.

**Comment by Naxulanth** [comment]
Hello, I've been a bit busy lately so I couldn't look into this.

I'm on DD-WRT (k3x mega build) right now, tried the latest 3.0.0 beta version.

![image](https://user-images.githubusercontent.com/28110882/40750995-ffba3af0-6471-11e8-87a8-7c4a26df7003.png)

I made sure that the entire directory has full permissions, but still getting the occasional permission denied error.

**Comment by 42Kmi** [comment]
How recently did you download? My most recent update was 2 days ago

**Comment by 42Kmi** [comment]
Ah, got it now. I've been running it my usual way for so long that I forgot
about that output. That's normal. Instead, run "./lagdrop/lagdrop.sh ps4 &>
/dev/null &"

That will hide that output and run it in the background so you can use the
terminal for other things. You should be able to see that LagDrop is
running if you run ps.

I can try to adjust it so all that output isn't shown when running without
"&> /dev/null". That only appears when peers aren't connect.

Thanks!
